-- Run in the Capella Query editor after creating the streaming bucket.
-- Definitions match StreamAI 1.0.0 provisioning.
CREATE SCOPE `streaming`.`catalogue` IF NOT EXISTS;
CREATE SCOPE `streaming`.`viewers` IF NOT EXISTS;
CREATE SCOPE `streaming`.`recommendations` IF NOT EXISTS;
CREATE SCOPE `streaming`.`operations` IF NOT EXISTS;
CREATE SCOPE `streaming`.`telemetry` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`catalogue`.`titles` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`catalogue`.`people` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`catalogue`.`genres` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`viewers`.`profiles` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`viewers`.`watch_history` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`viewers`.`interactions` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`viewers`.`app_state` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`recommendations`.`generated` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`recommendations`.`traces` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`recommendations`.`plan_cache` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`operations`.`ingestion_jobs` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`operations`.`entitlements` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`operations`.`agent_catalog` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`operations`.`action_receipts` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`telemetry`.`ai_metrics` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`telemetry`.`showcase_state` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`telemetry`.`experiments` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`telemetry`.`evaluations` IF NOT EXISTS;
CREATE COLLECTION `streaming`.`telemetry`.`profile_snapshots` IF NOT EXISTS;
CREATE PRIMARY INDEX IF NOT EXISTS ON `streaming`.`catalogue`.`titles`;
CREATE INDEX IF NOT EXISTS ix_titles_popularity ON `streaming`.`catalogue`.`titles`(popularity DESC, voteAverage DESC);
CREATE INDEX IF NOT EXISTS ix_titles_type_year ON `streaming`.`catalogue`.`titles`(contentType, releaseYear DESC);
CREATE INDEX IF NOT EXISTS ix_titles_type_genre ON `streaming`.`catalogue`.`titles`(contentType, DISTINCT ARRAY LOWER(g) FOR g IN genres END);
CREATE INDEX IF NOT EXISTS ix_titles_analytics ON `streaming`.`catalogue`.`titles`(contentType, releaseYear, originalLanguage, voteAverage, runtimeMinutes, episodeRuntimeMinutes);
CREATE PRIMARY INDEX IF NOT EXISTS ON `streaming`.`viewers`.`profiles`;
CREATE INDEX IF NOT EXISTS ix_watch_viewer_time ON `streaming`.`viewers`.`watch_history`(viewerId, lastWatchedAt DESC, progressPct, titleId);
CREATE INDEX IF NOT EXISTS ix_interactions_viewer_time ON `streaming`.`viewers`.`interactions`(viewerId, timestamp DESC, action, titleId);
CREATE INDEX IF NOT EXISTS ix_traces_viewer_time ON `streaming`.`recommendations`.`traces`(viewerId, timestamp DESC, type);
CREATE INDEX IF NOT EXISTS ix_traces_viewer_session ON `streaming`.`recommendations`.`traces`(viewerId, sessionId, startedAt ASC, type);
CREATE INDEX IF NOT EXISTS ix_plan_cache_version_expiry ON `streaming`.`recommendations`.`plan_cache`(plannerVersion, toolSchemaVersion, expiresAt, semanticEligible);
CREATE INDEX IF NOT EXISTS ix_plan_cache_stats ON `streaming`.`recommendations`.`plan_cache`(`type`, semanticEligible, hitCount);
CREATE INDEX IF NOT EXISTS ix_entitlements_viewer ON `streaming`.`operations`.`entitlements`(viewerId, regionCode, subscriptionTier);
CREATE INDEX IF NOT EXISTS ix_agent_catalog_type_name ON `streaming`.`operations`.`agent_catalog`(type, name, version);
CREATE INDEX IF NOT EXISTS ix_action_receipts_viewer_time ON `streaming`.`operations`.`action_receipts`(viewerId, timestamp DESC, action, titleId);
CREATE PRIMARY INDEX IF NOT EXISTS ON `streaming`.`telemetry`.`ai_metrics`;
CREATE INDEX IF NOT EXISTS ix_ai_metrics_viewer_time ON `streaming`.`telemetry`.`ai_metrics`(viewerId, updatedAt DESC);
CREATE PRIMARY INDEX IF NOT EXISTS ON `streaming`.`telemetry`.`showcase_state`;
CREATE INDEX IF NOT EXISTS ix_experiments_viewer_time ON `streaming`.`telemetry`.`experiments`(viewerId, timestamp DESC, type);
CREATE INDEX IF NOT EXISTS ix_evaluations_viewer_time ON `streaming`.`telemetry`.`evaluations`(viewerId, timestamp DESC, type);
CREATE INDEX IF NOT EXISTS ix_profile_snapshots_viewer_time ON `streaming`.`telemetry`.`profile_snapshots`(viewerId, timestamp DESC, recommendationVersion);
CREATE INDEX IF NOT EXISTS ix_usage_ledger_time ON `streaming`.`telemetry`.`ai_metrics`(`type`, timestamp, ledgerId, id);
